spring:
  application:
    name: Gestor
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
    jpa:
      format-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
        javax:
          persistence:
            query:
              timeout: 60000
      database: postgresql
      show-sql: true
server:
  port: 8085
  error:
    include-stacktrace: never
  address: localhost
  tomcat:
    connection-timeout: 40000
    max-wait: 100000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
junit:
  jupiter:
    execution:
      parallel:
        enabled: false